[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    '@uniswap/=lib/uniswap/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'solmate/=lib/solmate/',
    'permit2/=lib/permit2/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
